dist: xenial
language: python
python: - "3.6"
install:
 - pip install tox-travis
env:
 - ENV=pep8
 - ENV=py3
 - ENV=func-travis
script:
 - if [ $ENV = 'func-travis' ]; ten
      sudo apt-get -qq update;
      sudo apt-get -y install snapd;
      sudo snap install charm;
      sudo snap install lxd;
      sudo snap install juju --classic;
      sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
      sudo lxd waitready;
      sudo lxd init --auto;
      sudo usermod -a -G lxd travis;
      sudo su travis -c 'juju bootstrap --no-gui localhost';
      sudo su travis -c 'charm build';
      tox -c build/tox.ini --workdir /tmp/tox -e $ENV
    else
      tox -c tox.ini -e $ENV
    fi
  - if [ $ENV = 'func-travis' ]; then
    sudo su travis -c 'juju status -m $(juju models --format yaml|grep "^- name:.*zaza"|cut -f2 -d/)';
    fi
